source/Egharpay/Egharpay/Models/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Egharpay.Models
{
    public class DocumentViewModel
    {
        public byte[] DocumentBytes
        {
            get
            {
                if (Attachment != null)
                {
                    MemoryStream target = new MemoryStream();
                    Attachment.InputStream.CopyTo(target);
                    byte[] bytes = target.ToArray();
                    return bytes;
                }
                else if (!string.IsNullOrEmpty(DocumentBytesString))
                {
                    return Convert.FromBase64String(DocumentBytesString);
                }
                else
                {
                    return new byte[0];
                }
            }
        }

        public Guid DocumentDetailId { get; set; }

        public HttpPostedFileBase Attachment { get; set; }

        public int DocumentTypeId { get; set; }

        public string DocumentBytesString { get; set; }

        public string DocumentFileName { get; set; }

        public string StudentCode { get; set; }
    }
}

source/Egharpay/Egharpay/Controllers/CentreController.cs
using Egharpay.Business.Interfaces;
using Egharpay.Entity;
using Egharpay.Entity.Dto;
using Egharpay.Extensions;
using Egharpay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Egharpay.Controllers
{
    public class CentreController : BaseController
    {
        private readonly IEgharpayBusinessService _EgharpayBusinessService;

        public CentreController(IEgharpayBusinessService EgharpayBusinessService) : base(EgharpayBusinessService)
        {
            _EgharpayBusinessService = EgharpayBusinessService;
        }
        // GET: Centre
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(new BaseViewModel());
        }

        // GET: Centre/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var organisationId = UserOrganisationId;
            var viewModel = new CentreViewModel
            {
                Centre = new Centre
                {
                    OrganisationId = UserOrganisationId
                }
            };
            return View(viewModel);
        }

        // POST: Centre/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CentreViewModel centreViewModel)
        {
            var organisationId = UserOrganisationId;
            if (ModelState.IsValid)
            {
                centreViewModel.Centre.OrganisationId = UserOrganisationId;
                centreViewModel.Centre = EgharpayBusinessService.CreateCentre(UserOrganisationId, centreViewModel.Centre);
                return RedirectToAction("Index");
            }
            return View(centreViewModel);
        }

        // GET: Centre/Edit/{id}
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var centre = EgharpayBusinessService.RetrieveCentre(UserOrganisationId, id.Value);
            if (centre == null)
            {
                return HttpNotFound();
            }
            var viewModel = new CentreViewModel
            {
                Centre = centre

            };
            return View(viewModel);
        }

        // POST: Centre/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CentreViewModel centreViewModel)
        {
            if (ModelState.IsValid)
            {
                centreViewModel.Centre.OrganisationId = UserOrganisationId;
                return RedirectToAction("Index");
            }
            var viewModel = new CentreViewModel
            {
                Centre = centreViewModel.Centre
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult List(Paging paging, List<OrderBy> orderBy)
        {
            return this.JsonNet(EgharpayBusinessService.RetrieveCentres(UserOrganisationId, orderBy, paging));
        }

    }
}

source/Egharpay/Egharpay/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Egharpay.Business.Interfaces;
using Egharpay.Entity.Dto;
using Egharpay.Extensions;
using System.IO;
using Egharpay.Document.Interfaces;
using Egharpay.Models;

namespace Egharpay.Controllers
{
    public class DocumentController : BaseController
    {
        private readonly IDocumentService _documentService;
        public DocumentController(IEgharpayBusinessService EgharpayBusinessService, IDocumentService documentService) : base(EgharpayBusinessService)
        {
            _documentService = documentService;
        }
        // GET: Document
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StudentDocument(string studentCode, Paging paging, List<OrderBy> orderBy)
        {
            return this.JsonNet(EgharpayBusinessService.RetrieveDocuments(UserOrganisationId, e => e.CentreId == UserCentreId && e.StudentCode == studentCode, orderBy, paging));
        }
        [HttpPost]
        public ActionResult List(Paging paging, List<OrderBy> orderBy)
        {
            return this.JsonNet(null);
        }

        public ActionResult Download(Guid id)
        {
            var document = EgharpayBusinessService.RetrieveDocument(UserOrganisationId, id);
            return File(System.IO.File.ReadAllBytes(document.Location), "application/pdf", document.FileName);
        }

        [HttpPost]
        public ActionResult DocumentTypes()
        {
            return this.JsonNet(EgharpayBusinessService.RetrieveDocumentTypes(UserOrganisationId));
        }

        [HttpPost]
        public void CreateDocument(DocumentViewModel documentViewModel)
        {
            
        }
    }
}

source/Egharpay/Egharpay/Controllers/PersonnelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Egharpay.Attributes;
using Egharpay.Business.Interfaces;
using Egharpay.Entity;
using Egharpay.Entity.Dto;
using Egharpay.Extensions;
using Egharpay.Models;
using Egharpay.Models.Authorization;

namespace Egharpay.Controllers
{
    [Authorize]
    public class PersonnelController : BaseController
    {
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        private IPersonnelBusinessService _personnelBusinessService;
        private IEgharpayBusinessService _egharpayBusinessService;

        public PersonnelController(IPersonnelBusinessService personnelBusinessService, IEgharpayBusinessService egharpayBusinessService) : base(egharpayBusinessService)
        {
            _personnelBusinessService = personnelBusinessService;
            _egharpayBusinessService = egharpayBusinessService;
        }

        // GET: Personnel
        [AuthorizePersonnel(Roles = "Admin,User")]
        public ActionResult Index()
        {
            return View(new BaseViewModel());
        }

        // GET: Personnel/Profile/{id}
        [AuthorizePersonnel(Roles = "Admin,User")]
        public async Task<ActionResult> Profile(int id)
        {
            var personnel = await _personnelBusinessService.RetrievePersonnel(UserOrganisationId, id);
            if (personnel == null)
            {
                return HttpNotFound();
            }
            var isAdmin = User.IsInAnyRoles("Admin");
            if (!isAdmin)
            {
            }
            var viewModel = new PersonnelProfileViewModel
            {
                Personnel = personnel,
                //Permissions = EgharpayBusinessService.RetrievePersonnelPermissions(isAdmin, UserOrganisationId, UserPersonnelId, id),
                //PhotoBytes = EgharpayBusinessService.RetrievePhoto(organisationId, id)
            };
            return View(viewModel);
        }


        // GET: Personnel/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var centres = EgharpayBusinessService.RetrieveCentres(UserOrganisationId, e => true);
            var viewModel = new PersonnelProfileViewModel
            {

                Centres = new SelectList(centres, "CentreId", "Name"),
                Personnel = new Personnel
                {
                    OrganisationId = UserOrganisationId,
                    DOB = DateTime.Today,
                    Title = "Mr",
                    Forenames = "A",
                    Surname = "B",
                    Email = string.Format("{0}@hr.com", Guid.NewGuid()),
                    Address1 = "Address1",
                    Postcode = "POST CODE",
                    Telephone = "12345678",
                    NINumber = "NZ1234567",
                },
            };
            return View(viewModel);
        }

        // POST: Personnel/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PersonnelProfileViewModel personnelViewModel)
        {
            // check if user with this email already exists for the current organisation
            // var centres = EgharpayBusinessService.RetrieveCentres(UserOrganisationId, e => true);
            var userExists = UserManager.FindByEmail(personnelViewModel.Personnel.Email);
            // personnelViewModel.Centres = new SelectList(centres, "CentreId", "Name");
            if (userExists != null)
                ModelState.AddModelError("", string.Format("An account already exists for the email address {0}", personnelViewModel.Personnel.Email));

            if (ModelState.IsValid)
            {
                //Create Personnel
                personnelViewModel.Personnel.CentreId = personnelViewModel.Personnel.CentreId == 0 ? UserCentreId : personnelViewModel.Personnel.CentreId;
                var result = await _personnelBusinessService.CreatePersonnel(personnelViewModel.Personnel);
                if (result.Succeeded)
                {
                    CreateUserAndRole(personnelViewModel.Personnel);
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", result.Exception);
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }

            return View(personnelViewModel);
        }

        private IdentityResult CreateUserAndRole(Personnel personnel)
        {
            var createUser = new ApplicationUser
            {
                UserName = personnel.Email,
                Email = personnel.Email,
                OrganisationId = UserOrganisationId,
                PersonnelId = personnel.PersonnelId,
                CentreId = personnel.CentreId
            };

            var roleId = RoleManager.Roles.FirstOrDefault(r => r.Name == "User").Id;
            createUser.Roles.Add(new IdentityUserRole { UserId = createUser.Id, RoleId = roleId });

            var result = UserManager.Create(createUser, "Password1!");
            return result;
        }

        [AuthorizePersonnel(Roles = "Admin,User")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var personnel = await _personnelBusinessService.RetrievePersonnel(UserOrganisationId, id.Value);
            if (personnel == null)
            {
                return HttpNotFound();
            }
            //   var centres = EgharpayBusinessService.RetrieveCentres(UserOrganisationId, e => true);
            personnel.Email = UserManager.FindByPersonnelId(personnel.PersonnelId)?.Email;
            var viewModel = new PersonnelProfileViewModel
            {
                //        Centres = new SelectList(centres, "CentreId", "Name"),
                Personnel = personnel
            };
            return View(viewModel);
        }

        // POST: Personnels/Edit/{id}
        [AuthorizePersonnel(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PersonnelProfileViewModel personnelViewModel)
        {
            if (ModelState.IsValid)
            {

                var resultData = await _personnelBusinessService.UpdatePersonnel(personnelViewModel.Personnel);
                if (resultData.Succeeded)
                {
                    var editUser = UserManager.FindByPersonnelId(personnelViewModel.Personnel.PersonnelId);
                    editUser.Email = personnelViewModel.Personnel.Email;

                    var result = UserManager.Update(editUser);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                }
                ModelState.AddModelError("", resultData.Exception);
                foreach (var error in resultData.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }
            var viewModel = new PersonnelProfileViewModel
            {
                Personnel = personnelViewModel.Personnel
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UploadPhoto(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {

                        byte[] fileData = null;
                        using (var binaryReader = new BinaryReader(file.InputStream))
                        {
                            fileData = binaryReader.ReadBytes(file.ContentLength);
                        }
                        //EgharpayBusinessService.UploadPhoto(UserOrganisationId, id.Value,  fileData);
                    }
                }
                return this.JsonNet("");
            }
            catch (Exception ex)
            {
                return this.JsonNet(ex);
            }

        }

        [HttpPost]
        public ActionResult DeletePhoto(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                //EgharpayBusinessService.DeletePhoto(UserOrganisationId, id.Value);
                return this.JsonNet("");
            }
            catch (Exception ex)
            {
                return this.JsonNet(ex);
            }

        }

        [HttpPost]
        public async Task<ActionResult> List(Paging paging, List<OrderBy> orderBy)
        {
            var data = await _personnelBusinessService.RetrievePersonnels(UserCentreId, orderBy, paging);
            return this.JsonNet(data);
        }

        [HttpPost]
        public async Task<ActionResult> Search(string searchKeyword, Paging paging, List<OrderBy> orderBy)
        {
            return this.JsonNet(await _personnelBusinessService.Search(UserCentreId, searchKeyword, orderBy, paging));
        }

source/Egharpay/Egharpay/Views/Shared/_Colour.cshtml
@{
    int squareRoot = Convert.ToInt32(Math.Sqrt(Model.Count));
    int counter = 0;
}
<div class="dropdown">
    <button class="btn btn-default btn-md dropdown-toggle required" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span id="ColourDropDown" class="square" style="background-color:#@ViewData["ColourHex"]"></span>
        <span class="caret"></span>
    </button>
    <div class="table-responsive dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <table class="table-condensed">
            <tbody>
                <tr>
                    @foreach (var Colour in Model)
                    {
                        <td><a href="#" onclick="SetSelectedColour(@Colour.ColourId,'@Colour.Hex')"><span class="square" style="background-color: #@Colour.Hex"></span></a></td>
                        counter++;
                        if (counter == squareRoot)
                        {
                            counter = 0;
                            @Html.Raw(" </tr><tr>");
                        }
                    }
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    function SetSelectedColour(ColourId, ColourHex) {
        document.getElementById("ColourDropDown").style.backgroundColor = "#" + ColourHex;
        document.getElementById("ColourId").value = ColourId;
    }
</script>

source/Egharpay/Egharpay/Views/Shared/_ColourLegend.cshtml
<ui-select ng-model="model.showColourBy" ng-change="model.filterSelected()">
    <ui-select-match>
        <span ng-bind="$select.selected.text"></span>
    </ui-select-match>
    <ui-select-choices repeat="item in (model.chartColours | filter: $select.search) track by item.id">
        <span ng-bind="item.text"></span>
    </ui-select-choices>
</ui-select>
<div ng-repeat="Legend in (model.showColourBy.id == 1 && (model.organisationalChartViewModel.PersonnelDetailFilter.Company) || (model.showColourBy.id == 2 && (model.organisationalChartViewModel.PersonnelDetailFilter.Division) || (model.organisationalChartViewModel.PersonnelDetailFilter.Department)))">
    <span class="square" ng-style="{'background-color' : '#' + Legend.Hex }"></span> {{Legend.Name}}
</div>

source/Egharpay/Egharpay/Views/Shared/_Counselling.cshtml
@using Egharpay.Extensions
@model Egharpay.Models.CounsellingViewModel
<div class="form-control-required-example"> = Required</div>

@Html.HiddenFor(m => m.Counselling.CounsellingId)
@Html.HiddenFor(m => m.Counselling.EnquiryId)


<div class="form-group">
    @Html.LabelFor(model => model.Counselling.CourseOfferedId, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
    <div class="col-md-6 col-sm-6 col-xs-12">
        @Html.DropDownListFor(model => model.Counselling.CourseOfferedId, Model.Courses, "Select Course", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Counselling.CourseOfferedId, "", new { @class = "help-block" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Counselling.PreferTiming, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
    <div class="col-md-6 col-sm-6 col-xs-12">
        @Html.TextBoxFor(model => model.Counselling.PreferTiming, new { @class = "form-control col-md-7 col-xs-12" })
        @Html.ValidationMessageFor(model => model.Counselling.PreferTiming, "", new { @class = "help-block" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Psychomatric Test Done</label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div id="psychomatricTest" class="btn-group" data-toggle="buttons">
            <label id="psychomatricTestYes" class='@(Model.Counselling.PsychomatricTest == "Yes" ? "btn btn-primary active" : "btn btn-default")' data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                @Html.RadioButtonFor(model => model.Counselling.PsychomatricTest, "Yes")
                <input type="radio" name="psychomatricTest" value="Yes" data-parsley-multiple="gender"> &nbsp; Yes &nbsp;
            </label>
            <label id="psychomatricTestNo" class='@(Model.Counselling.PsychomatricTest == "No" ? "btn btn-primary active" : "btn btn-default")' data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                @Html.RadioButtonFor(model => model.Counselling.PsychomatricTest, "No")
                <input type="radio" name="psychomatricTest" value="No" data-parsley-multiple="gender"> No
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Counselling.ConversionProspect, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
    <div class="col-md-6 col-sm-6 col-xs-12">
        @Html.DropDownListFor(model => model.Counselling.ConversionProspect, Model.ConversionProspectList, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Counselling.ConversionProspect, "", new { @class = "help-block" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Counselling.Remarks, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
    <div class="col-md-6 col-sm-6 col-xs-12">
        @Html.EditorFor(model => model.Counselling.Remarks, new { @class = "form-control col-md-7 col-xs-12" })
        @Html.ValidationMessageFor(model => model.Counselling.Remarks, "", new { @class = "help-block" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Counselling.RemarkByBranchManager, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
    <div class="col-md-6 col-sm-6 col-xs-12">
        @Html.EditorFor(model => model.Counselling.RemarkByBranchManager, new { @class = "form-control col-md-7 col-xs-12" })
        @Html.ValidationMessageFor(model => model.Counselling.RemarkByBranchManager, "", new { @class = "help-block" })
    </div>
</div>

source/Egharpay/Egharpay/Views/Shared/_Layout.cshtml
@using Egharpay.Extensions
@model Egharpay.Models.BaseViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Egharpay</title>
    @Styles.Render("~/Content/bower")
    @Styles.Render("~/Content/Inspinia")
    @Styles.Render("~/Content/bower/gentelella")
    @Styles.Render("~/Content/Application")
    <meta name="description" content="Egharpay" />
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container" ng-app="Egharpay">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="/" class="site_title"><i class="fa fa-leaf"></i> <span>Egharpay</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li>
                                    <a href='@Url.Action("Index", "Home")'><i class="fa fa-home"></i> Home </a>
                                </li>
                                @if (User.IsInAnyRoles("Admin"))
                                {
                                    <li>
                                        <a><i class="fa fa-cogs"></i> Mobilization <span class="fa fa-chevron-up"></span></a>
                                        <ul class="nav child_menu"></ul>
                                    </li>
                                }
                                @*@if (User.IsInAnyRoles("Admin"))
                                {*@
                                    <li>
                                        <a><i class="fa fa-cogs"></i> Settings <span class="fa fa-chevron-up"></span></a>
                                        <ul class="nav child_menu">
                                            @if (User.IsInAnyRoles("SuperAdmin"))
                                            {
                                                <li><a href="@Url.Action("Index", "Organisation")">Organisation</a></li>
                                            }
                                            <li><a href='@Url.Action("Index", "Centre")'>Centre</a></li>
                                            <li><a href='@Url.Action("Index", "Personnel")'>Personnel</a></li>
                                            <li><a href="@Url.Action("Index", "User")">Users</a></li>
                                        </ul>
                                    </li>
                                @*}*@
                            </ul>
                        </div>

                    </div>
                    <!-- /sidebar menu -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#">
                                    <h2 class="user-profile">
                                        @Model.CentreName
                                    </h2>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    @*<img src="images/img.jpg" alt="">*@ @User.Identity.Name
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li>@Html.ActionLink("Profile", "Profile", "Personnel", new { id = Model.PersonnelId }, null)</li>
                                    @*<li>
                                            <a href="javascript:;">
                                                <span class="badge bg-red pull-right">50%</span>
                                                <span>Settings</span>
                                            </a>
                                        </li>*@
                                    @*<li><a href="javascript:;">Help</a></li>*@
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                @RenderBody()
                <div class="clearfix"></div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-left">
                    <div>
                        <h2><i class="fa fa-leaf"></i> Egharpay</h2>
                        <p>&copy; @DateTime.Today.Year All Rights Reserved. Egharpay</p>
                    </div>
                </div>
                <div class="pull-right">
                    <div>
                        <h4><i class="fa fa-code-fork"></i> @ViewContext.Controller.GetType().Assembly.GetName().Version</h4>
                    </div>
                </div>

                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    @using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm" }))
    {
        @Html.AntiForgeryToken()
    }
    @Scripts.Render("~/Scripts/bower")
    @Scripts.Render("~/Scripts/Inspinia")
    @Scripts.Render("~/Scripts/bower/gentelella")
    @Scripts.Render("~/Scripts/Application")
    @RenderSection("scripts", required: false)
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcqnWhG3ozWTY6ONe-u4_Y2pk_iTiST9Y&callback=initMap" async defer></script>

    <script>
        $(document).ready(function () {
            $(".btn-primary").mouseover(function () {
                if ($(".btn-primary").text().trim() == "Back to list") {
                    $('input[type="text"]').rules('remove', 'required');
                }
            });
            $(".btn-primary").mouseout(function () {
                if ($(".btn-primary").text().trim() == "Back to list") {
                    $('input[type="text"]').rules('add', 'required');
                }
            });
            var map;
            function initMap() {
                var mapCenter = new google.maps.LatLng(47.6145, -122.3418); //Google map Coordinates
                map = new google.maps.Map($("#map")[0], {
                    center: mapCenter,
                    zoom: 8
                });
            }

            $("#find_btn").click(function () {
                if ("geolocation" in navigator) {
                    navigator.geolocation.getCurrentPosition(function (position) {
                        infoWindow = new google.maps.InfoWindow({ map: map });
                        var pos = { lat: position.coords.latitude, lng: position.coords.longitude };
                        infoWindow.setPosition(pos);
                        infoWindow.setContent("Found your location <br />Lat : " + position.coords.latitude + " </br>Lang :" + position.coords.longitude);
                        map.panTo(pos);
                    });
                } else {
                    console.log("Browser doesn't support geolocation!");
                }
            });
        });
    </script>
</body>
</html>